<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class Product extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
//        return parent::toArray($request);
        return [
            'status' => 200,
            'message' => 'yeu cau thanh cong',
            'id' => $this->id,
            'name_product' => $this->name_product,
            'price' => $this->price,
        ];
    }
    public function with($request)
    {
        //return parent::with($request); // TODO: Change the autogenerated stub
        return [
            'version' => '1.0.0',
            'author' => 'Lee Anh'
        ];
    }
}
